version: "2"

services:

  app:
    # Build application using Dockerfile contained in application subfolder
    build: ./application
    # Name image
    image: openempi-app
    # Enable healthchecks on the images so containers can automatically restart if they stop responding
    labels:
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    # Map application container port 8080 to docker port 8080
    ports:
      - "8080:8080"
    # Do not start application container until postgres container is started
    depends_on:
      - postgres

  postgres:
    # Build database using Dockerfile contained in postgres subfolder
    build: ./postgres
    # Name image
    image: openempi-db
    # Enable healthchecks on the images so containers can automatically restart if they stop responding
    labels:
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    # Map application container port 5432 to docker port 5432
    ports:
      - "5432:5432"
      